#include "EditorTexts.h"

namespace finger_drum::texts
{
    const EditorTextSet &Editor(const Language language) noexcept
    {
        static constexpr EditorTextSet Korean{
            {L"패턴", L"박자표", L"메타데이터", L"이펙트", L"오디오"},
            L"저장",
            L"저장 *",
            L"파일",
            L"저장하기",
            L"롱노트 끝 위치를 클릭하세요 · 도구 변경/Escape: 취소",
            L"전체 악보 뷰",
            L"실시간 뷰",
            L"박자 디바이더",
            L"직접 입력",
            L"박자 분할 (1/N)",
            L"도구",
            L"박자표 · BPM / 마디 길이",
            L"마디     위치          종류            값",
            L"마디",
            L"지연",
            L"삭제",
            L"시작 마디",
            L"변경 위치 N/D",
            L"BPM 추가 / 수정",
            L"마디 길이 N/D",
            L"마디 길이 적용",
            L"넘친 노트는 초과 박자를 유지해 다음 마디로 이동합니다.\n마디 밖의 BPM/이펙트는 먼저 이동해 주세요.",
            L"메타데이터",
            L"YMM 상대 경로",
            L"패턴 이름",
            L"제작자 (한 줄에 한 명)",
            L"태그 (한 줄에 하나)",
            L"오프셋 (ms)",
            L"기본 BPM",
            L"히트사운드 테이블",
            L"히트사운드 표는 YME에 저장하며 경로도 YME 기준입니다. 예: 1: Sounds/pop.wav\n"
            L"YMP의 Effect file 경로에 저장합니다. 경로가 없으면 같은 이름의 YME를 생성합니다. Ctrl+S: 저장",
            L"이펙트",
            L"시작 마디 / 박자      종류           값 / 참조 인덱스",
            {L"히트사운드 볼륨", L"마디선", L"개별 속도 (Separate)", L"전체 속도 (Whole)"},
            L"시작 박자",
            L"끝 마디 (선택)",
            L"끝 박자 (선택)",
            L"히트사운드 인덱스",
            L"시작 값 (마디선 0/1)",
            L"끝 값",
            {L"선형", L"지수", L"조화수열"},
            L"오디오 버스",
            L"추가 / 같은 위치 수정",
            L"오디오 분석 / 히트사운드",
            L"현재 시간 (ms)",
            L"마우스 휠: 마디 이동 · ← / →: 1ms · Ctrl+S: 저장",
            L"오디오 분석 중…",
            L"타임라인",
            L"음악 파형",
            L"음악 FFT 스펙트로그램",
            L"예상 히트사운드 FFT 스펙트로그램",
            L"저장하지 않은 변경을 버리고 나가시겠습니까?",
            L"FingerDrum 에디터",
            L"확인",
            L"취소"};

        static constexpr EditorTextSet English{
            {L"PATTERN", L"TIMING", L"METADATA", L"EFFECTS", L"AUDIO"},
            L"SAVE",
            L"SAVE *",
            L"File",
            L"Save",
            L"Click the long-note end · Change tool/Escape: cancel",
            L"SCORE VIEW",
            L"REALTIME VIEW",
            L"BEAT DIVIDER",
            L"DIRECT INPUT",
            L"Beat division (1/N)",
            L"TOOLS",
            L"TIMING · BPM / MEASURE LENGTH",
            L"MEASURE     POSITION      TYPE            VALUE",
            L"Measure",
            L"Delay",
            L"DELETE",
            L"START MEASURE",
            L"POSITION N/D",
            L"ADD / UPDATE BPM",
            L"MEASURE LENGTH N/D",
            L"APPLY MEASURE LENGTH",
            L"Overflowing notes keep their excess beat and move to the next measure.\nMove BPM/effects outside the "
            L"measure first.",
            L"METADATA",
            L"YMM RELATIVE PATH",
            L"PATTERN NAME",
            L"MAKERS (ONE PER LINE)",
            L"TAGS (ONE PER LINE)",
            L"OFFSET (ms)",
            L"BASE BPM",
            L"HIT-SOUND TABLE",
            L"Hit-sound table paths are relative to the YME, for example 1: Sounds/pop.wav.\n"
            L"Save uses Effect file in the YMP, or creates a matching YME when absent. Ctrl+S: save",
            L"EFFECTS",
            L"START MEASURE / BEAT    TYPE            VALUE / REFERENCE INDEX",
            {L"HIT-SOUND VOLUME", L"MEASURE LINE", L"SEPARATE SPEED", L"WHOLE SPEED"},
            L"START BEAT",
            L"END MEASURE (OPTIONAL)",
            L"END BEAT (OPTIONAL)",
            L"HIT-SOUND INDEX",
            L"START VALUE (MEASURE LINE 0/1)",
            L"END VALUE",
            {L"Linear", L"Exponential", L"Harmonic"},
            L"AUDIO BUS",
            L"ADD / UPDATE AT POSITION",
            L"AUDIO ANALYSIS / HIT SOUNDS",
            L"CURRENT TIME (ms)",
            L"Mouse wheel: move measures · ← / →: 1 ms · Ctrl+S: save",
            L"ANALYZING AUDIO…",
            L"TIMELINE",
            L"MUSIC WAVEFORM",
            L"MUSIC FFT SPECTROGRAM",
            L"EXPECTED HIT-SOUND FFT SPECTROGRAM",
            L"Discard unsaved changes and leave?",
            L"FingerDrum Editor",
            L"OK",
            L"Cancel"};
        return language == Language::Korean ? Korean : English;
    }
} // namespace finger_drum::texts
